# Medical Appointment No Shows Capstone

### 4. Feature Engineering - PreProcessing - Training Data Development

In [1]:
#Import necessary libraries
import pandas as pd
import numpy as np

# Plotting modules
import matplotlib.pyplot as plt
import seaborn as sns

# File system manangement
import os,sys

# Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell  
InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline
%matplotlib notebook

In [2]:
# SKLEARN
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PowerTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

from sklearn.compose import ColumnTransformer

In [3]:
path = 'data/wrangle_csv.csv'
df = pd.read_csv(path, index_col=None, parse_dates=["ScheduledDay","AppointmentDay"]) 
df.head()

Gender        ScheduledDay      AppointmentDay  Age       Neighborhood  \
0      F 2016-04-29 18:38:08 2016-04-29 18:38:08   62    JARDIM DA PENHA   
1      M 2016-04-29 16:08:27 2016-04-29 16:08:27   56    JARDIM DA PENHA   
2      F 2016-04-29 16:19:04 2016-04-29 16:19:04   62      MATA DA PRAIA   
3      F 2016-04-29 17:29:31 2016-04-29 17:29:31    8  PONTAL DE CAMBURI   
4      F 2016-04-29 16:07:23 2016-04-29 16:07:23   56    JARDIM DA PENHA   

   Scholarship  Hypertension  Diabetes  Alcoholism  Handicap  SMSSent NoShow  \
0            0             1         0           0         0        0     No   
1            0             0         0           0         0        0     No   
2            0             0         0           0         0        0     No   
3            0             0         0           0         0        0     No   
4            0             1         1           0         0        0     No   

   WaitingDays ScheduledTime  ScheduledHour ScheduledDayWeekDay  \
0            0      18:38:08             18              Friday   
1            0      16:08:27             16              Friday   
2            0      16:19:04             16              Friday   
3            0      17:29:31             17              Friday   
4            0      16:07:23             16              Friday   

  AppointmentDayWeekName ScheduledDayMonthName AppointmentDayMonthName  
0                 Friday                 April                   April  
1                 Friday                 April                   April  
2                 Friday                 April                   April  
3                 Friday                 April                   April  
4                 Friday                 April                   April

In [4]:
df.var()

Age              533.760165
Scholarship        0.088617
Hypertension       0.158347
Diabetes           0.066706
Alcoholism         0.029479
Handicap           0.026064
SMSSent            0.217977
WaitingDays      225.835733
ScheduledHour     10.344366
dtype: float64

In [8]:
df['ScheduledDay_Y'] = df['ScheduledDay'].dt.year
df['ScheduledDay_D'] = df['ScheduledDay'].dt.day
df.drop(['ScheduledDay'], axis=1, inplace=True)

df['AppointmentDay_Y'] = df['AppointmentDay'].dt.year
df['AppointmentDay_D'] = df['AppointmentDay'].dt.day
df.drop(['AppointmentDay'], axis=1, inplace=True)

df.drop(['ScheduledTime'], axis=1, inplace=True)

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110517 entries, 0 to 110516
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype 
---  ------                   --------------   ----- 
 0   Gender                   110517 non-null  object
 1   Age                      110517 non-null  int64 
 2   Neighborhood             110517 non-null  object
 3   Scholarship              110517 non-null  int64 
 4   Hypertension             110517 non-null  int64 
 5   Diabetes                 110517 non-null  int64 
 6   Alcoholism               110517 non-null  int64 
 7   Handicap                 110517 non-null  int64 
 8   SMSSent                  110517 non-null  int64 
 9   NoShow                   110517 non-null  object
 10  WaitingDays              110517 non-null  int64 
 11  ScheduledHour            110517 non-null  int64 
 12  ScheduledDayWeekDay      110517 non-null  object
 13  AppointmentDayWeekName   110517 non-null  object
 14  ScheduledDayMonthNam

In [10]:
df.select_dtypes(include=[object])

Gender       Neighborhood NoShow ScheduledDayWeekDay  \
0           F    JARDIM DA PENHA     No              Friday   
1           M    JARDIM DA PENHA     No              Friday   
2           F      MATA DA PRAIA     No              Friday   
3           F  PONTAL DE CAMBURI     No              Friday   
4           F    JARDIM DA PENHA     No              Friday   
...       ...                ...    ...                 ...   
110512      F        MARIA ORTIZ     No             Tuesday   
110513      F        MARIA ORTIZ     No             Tuesday   
110514      F        MARIA ORTIZ     No           Wednesday   
110515      F        MARIA ORTIZ     No           Wednesday   
110516      F        MARIA ORTIZ     No           Wednesday   

       AppointmentDayWeekName ScheduledDayMonthName AppointmentDayMonthName  
0                      Friday                 April                   April  
1                      Friday                 April                   April  
2                      Friday                 April                   April  
3                      Friday                 April                   April  
4                      Friday                 April                   April  
...                       ...                   ...                     ...  
110512                Tuesday                   May                    June  
110513                Tuesday                   May                    June  
110514                Tuesday                 April                    June  
110515                Tuesday                 April                    June  
110516                Tuesday                 April                    June  

[110517 rows x 7 columns]

## LabelEncoder

In [5]:
df_le1 = df.loc[:, ['Gender','NoShow','Neighborhood',
                       'ScheduledDayWeekDay','AppointmentDayWeekName','ScheduledDayMonthName','AppointmentDayMonthName']]

In [6]:
le = LabelEncoder()

encoded = df_le1.apply(le.fit_transform)

dropped_cols = df.drop(columns=df_le1)

df_le = pd.concat([dropped_cols,encoded],axis=1)

In [7]:
df_le.head()

ScheduledDay      AppointmentDay  Age  Scholarship  Hypertension  \
0 2016-04-29 18:38:08 2016-04-29 18:38:08   62            0             1   
1 2016-04-29 16:08:27 2016-04-29 16:08:27   56            0             0   
2 2016-04-29 16:19:04 2016-04-29 16:19:04   62            0             0   
3 2016-04-29 17:29:31 2016-04-29 17:29:31    8            0             0   
4 2016-04-29 16:07:23 2016-04-29 16:07:23   56            0             1   

   Diabetes  Alcoholism  Handicap  SMSSent  WaitingDays ScheduledTime  \
0         0           0         0        0            0      18:38:08   
1         0           0         0        0            0      16:08:27   
2         0           0         0        0            0      16:19:04   
3         0           0         0        0            0      17:29:31   
4         1           0         0        0            0      16:07:23   

   ScheduledHour  Gender  NoShow  Neighborhood  ScheduledDayWeekDay  \
0             18       0       0            38                    0   
1             16       1       0            38                    0   
2             16       0       0            44                    0   
3             17       0       0            53                    0   
4             16       0       0            38                    0   

   AppointmentDayWeekName  ScheduledDayMonthName  AppointmentDayMonthName  
0                       0                      0                        0  
1                       0                      0                        0  
2                       0                      0                        0  
3                       0                      0                        0  
4                       0                      0                        0

## SKLEARN ONE HOT ENCODER 

In [8]:
categorical_features = ['Gender','NoShow','Neighborhood',
                       'ScheduledDayWeekDay','AppointmentDayWeekName','ScheduledDayMonthName','AppointmentDayMonthName']



ohe = OneHotEncoder(sparse=True, drop='first', handle_unknown='error')


encoded = pd.DataFrame(ohe.fit_transform(df_le[categorical_features]).toarray(), \
                                columns=ohe.get_feature_names(categorical_features))

dropped_cols = df.drop(columns=categorical_features)


#df_ohe = data_hot_encoded_drop.join(data_hot_encoded)
df_ohe = pd.concat([dropped_cols,encoded],axis=1)

df_ohe

ScheduledDay      AppointmentDay  Age  Scholarship  \
0      2016-04-29 18:38:08 2016-04-29 18:38:08   62            0   
1      2016-04-29 16:08:27 2016-04-29 16:08:27   56            0   
2      2016-04-29 16:19:04 2016-04-29 16:19:04   62            0   
3      2016-04-29 17:29:31 2016-04-29 17:29:31    8            0   
4      2016-04-29 16:07:23 2016-04-29 16:07:23   56            0   
...                    ...                 ...  ...          ...   
110512 2016-05-03 09:15:35 2016-06-07 00:00:00   56            0   
110513 2016-05-03 07:27:33 2016-06-07 00:00:00   51            0   
110514 2016-04-27 16:03:52 2016-06-07 00:00:00   21            0   
110515 2016-04-27 15:09:23 2016-06-07 00:00:00   38            0   
110516 2016-04-27 13:30:56 2016-06-07 00:00:00   54            0   

        Hypertension  Diabetes  Alcoholism  Handicap  SMSSent  WaitingDays  \
0                  1         0           0         0        0            0   
1                  0         0           0         0        0            0   
2                  0         0           0         0        0            0   
3                  0         0           0         0        0            0   
4                  1         1           0         0        0            0   
...              ...       ...         ...       ...      ...          ...   
110512             0         0           0         0        1           34   
110513             0         0           0         0        1           34   
110514             0         0           0         0        1           40   
110515             0         0           0         0        1           40   
110516             0         0           0         0        1           40   

        ... AppointmentDayWeekName_5  ScheduledDayMonthName_1  \
0       ...                      0.0                      0.0   
1       ...                      0.0                      0.0   
2       ...                      0.0                      0.0   
3       ...                      0.0                      0.0   
4       ...                      0.0                      0.0   
...     ...                      ...                      ...   
110512  ...                      0.0                      0.0   
110513  ...                      0.0                      0.0   
110514  ...                      0.0                      0.0   
110515  ...                      0.0                      0.0   
110516  ...                      0.0                      0.0   

        ScheduledDayMonthName_2  ScheduledDayMonthName_3  \
0                           0.0                      0.0   
1                           0.0                      0.0   
2                           0.0                      0.0   
3                           0.0                      0.0   
4                           0.0                      0.0   
...                         ...                      ...   
110512                      0.0                      0.0   
110513                      0.0                      0.0   
110514                      0.0                      0.0   
110515                      0.0                      0.0   
110516                      0.0                      0.0   

        ScheduledDayMonthName_4  ScheduledDayMonthName_5  \
0                           0.0                      0.0   
1                           0.0                      0.0   
2                           0.0                      0.0   
3                           0.0                      0.0   
4                           0.0                      0.0   
...                         ...                      ...   
110512                      0.0                      0.0   
110513                      0.0                      0.0   
110514                      0.0                      0.0   
110515                      0.0                      0.0   
110516                      0.0                      0.0   

        ScheduledDayMonthName_6  Sche

In [9]:
ohe.categories_

[array([0, 1]),
 array([0, 1]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2])]

In [10]:
ohe.get_feature_names(input_features=categorical_features)

array(['Gender_1', 'NoShow_1', 'Neighborhood_1', 'Neighborhood_2',
       'Neighborhood_3', 'Neighborhood_4', 'Neighborhood_5',
       'Neighborhood_6', 'Neighborhood_7', 'Neighborhood_8',
       'Neighborhood_9', 'Neighborhood_10', 'Neighborhood_11',
       'Neighborhood_12', 'Neighborhood_13', 'Neighborhood_14',
       'Neighborhood_15', 'Neighborhood_16', 'Neighborhood_17',
       'Neighborhood_18', 'Neighborhood_19', 'Neighborhood_20',
       'Neighborhood_21', 'Neighborhood_22', 'Neighborhood_23',
       'Neighborhood_24', 'Neighborhood_25', 'Neighborhood_26',
       'Neighborhood_27', 'Neighborhood_28', 'Neighborhood_29',
       'Neighborhood_30', 'Neighborhood_31', 'Neighborhood_32',
       'Neighborhood_33', 'Neighborhood_34', 'Neighborhood_35',
       'Neighborhood_36', 'Neighborhood_37', 'Neighborhood_38',
       'Neighborhood_39', 'Neighborhood_40', 'Neighborhood_41',
       'Neighborhood_42', 'Neighborhood_43', 'Neighborhood_44',
       'Neighborhood_45', 'Neighborhood_46',

___

# LabelEncoder's Approach

### df_le1

In [8]:
df_le1 = df.loc[:, ['Gender', 'Neighborhood', 'NoShow']]

In [9]:
le = LabelEncoder()

df_le1['Gender'] = le.fit_transform(df_le1['Gender'])
df_le1['Neighborhood'] = le.fit_transform(df_le1['Neighborhood'])
df_le1['NoShow'] = le.fit_transform(df_le1['NoShow'])



df_le1.head()

Gender  Neighborhood  NoShow
0       0            38       0
1       1            38       0
2       0            44       0
3       0            53       0
4       0            38       0

### df_le2

In [11]:
df_le2 = df.loc[:]

In [12]:
le = LabelEncoder()

df_le2['Gender'] = le.fit_transform(df_le2['Gender'])
df_le2['Neighborhood'] = le.fit_transform(df_le2['Neighborhood'])
df_le2['NoShow'] = le.fit_transform(df_le2['NoShow'])

# use df.apply() to apply le.fit_transform to all columns
#df = df.apply(le.fit_transform)

df_le2.head()

Gender  Age  Neighborhood  Scholarship  Hypertension  Diabetes  Alcoholism  \
0       0   62            38            0             1         0           0   
1       1   56            38            0             0         0           0   
2       0   62            44            0             0         0           0   
3       0    8            53            0             0         0           0   
4       0   56            38            0             1         1           0   

   Handicap  SMSSent  NoShow  WaitingDays  ScheduledDay_Y  ScheduledDay_M  \
0         0        0       0           -1            2016               4   
1         0        0       0           -1            2016               4   
2         0        0       0           -1            2016               4   
3         0        0       0           -1            2016               4   
4         0        0       0           -1            2016               4   

   ScheduledDay_D  AppointmentDay_Y  AppointmentDay_M  AppointmentDay_D  
0              29              2016                 4                29  
1              29              2016                 4                29  
2              29              2016                 4                29  
3              29              2016                 4                29  
4              29              2016                 4                29

## Pandas Get_Dummies Approach

In [13]:
features = ['Gender','Neighborhood','NoShow']

df_gd = pd.concat([df,
                   pd.get_dummies(df[features], drop_first=True,
                   prefix=['G','N','Show'])], axis=1).drop(features, axis=1)

print(df_gd.shape)
df_gd.head()

(110517, 95)


Age  Scholarship  Hypertension  Diabetes  Alcoholism  Handicap  SMSSent  \
0   62            0             1         0           0         0        0   
1   56            0             0         0           0         0        0   
2   62            0             0         0           0         0        0   
3    8            0             0         0           0         0        0   
4   56            0             1         1           0         0        0   

   WaitingDays  ScheduledDay_Y  ScheduledDay_M  ...  N_SEGURANÇA DO LAR  \
0            0            2016               4  ...                   0   
1            0            2016               4  ...                   0   
2            0            2016               4  ...                   0   
3            0            2016               4  ...                   0   
4            0            2016               4  ...                   0   

   N_SOLON BORGES  N_SÃO BENEDITO  N_SÃO CRISTÓVÃO  N_SÃO JOSÉ  N_SÃO PEDRO  \
0               0               0                0           0            0   
1               0               0                0           0            0   
2               0               0                0           0            0   
3               0               0                0           0            0   
4               0               0                0           0            0   

   N_TABUAZEIRO  N_UNIVERSITÁRIO  N_VILA RUBIM  Show_Yes  
0             0                0             0         0  
1             0                0             0         0  
2             0                0             0         0  
3             0                0             0         0  
4             0                0             0         0  

[5 rows x 95 columns]

# Export Data

In [17]:
#LabelEncoder 1 
df_le1.to_csv('data/df_le1.csv',index=False)

In [18]:
#LabelEncoder 2
df_le2.to_csv('data/df_le2.csv',index=False)

In [14]:
#Get_dummies data
df_gd.to_csv('data/df_gd.csv',index=False)

In [83]:
#OneHotEncoder data
df_ohe.to_csv('data/df_ohe.csv',index=False)